#!/bin/bash

clang -Wp,-MD,net/ipv4/.route.o.d  -nostdinc -isystem /usr/bin/../lib/clang/19/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Wno-format-security -std=gnu89 -Werror=unknown-warning-option -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mstack-alignment=8 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -mno-global-merge -Wno-unused-but-set-variable -Wno-unused-const-variable -g -pg -mfentry -DCC_USING_NOP_MCOUNT -DCC_USING_FENTRY -fno-lto -flto=thin -fsplit-lto-unit -fvisibility=hidden -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-array-bounds -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Wno-error=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=./= -Wno-initializer-overrides -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-pointer-to-enum-cast -Wno-unaligned-access -Wno-cast-function-type-strict    -DKBUILD_BASENAME='"route"' -DKBUILD_MODNAME='"route"' -D__KBUILD_MODNAME=kmod_route -c -o net/ipv4/route.o net/ipv4/route.c

rm -f net/ipv4/built-in.a; llvm-ar cDPrST net/ipv4/built-in.a net/ipv4/route.o
# rm -f net/ipv4/built-in.a; llvm-ar cDPrST net/ipv4/built-in.a net/ipv4/route.o net/ipv4/inetpeer.o net/ipv4/protocol.o net/ipv4/ip_input.o net/ipv4/ip_fragment.o net/ipv4/ip_forward.o net/ipv4/ip_options.o net/ipv4/ip_output.o net/ipv4/ip_sockglue.o net/ipv4/inet_hashtables.o net/ipv4/inet_timewait_sock.o net/ipv4/inet_connection_sock.o net/ipv4/tcp.o net/ipv4/tcp_input.o net/ipv4/tcp_output.o net/ipv4/tcp_timer.o net/ipv4/tcp_ipv4.o net/ipv4/tcp_minisocks.o net/ipv4/tcp_cong.o net/ipv4/tcp_metrics.o net/ipv4/tcp_fastopen.o net/ipv4/tcp_rate.o net/ipv4/tcp_recovery.o net/ipv4/tcp_ulp.o net/ipv4/tcp_offload.o net/ipv4/datagram.o net/ipv4/raw.o net/ipv4/udp.o net/ipv4/udplite.o net/ipv4/udp_offload.o net/ipv4/arp.o net/ipv4/icmp.o net/ipv4/devinet.o net/ipv4/af_inet.o net/ipv4/igmp.o net/ipv4/fib_frontend.o net/ipv4/fib_semantics.o net/ipv4/fib_trie.o net/ipv4/fib_notifier.o net/ipv4/inet_fragment.o net/ipv4/ping.o net/ipv4/ip_tunnel_core.o net/ipv4/gre_offload.o net/ipv4/metrics.o net/ipv4/netlink.o net/ipv4/nexthop.o net/ipv4/sysctl_net_ipv4.o net/ipv4/proc.o net/ipv4/fib_rules.o net/ipv4/ipmr.o net/ipv4/ipmr_base.o net/ipv4/syncookies.o net/ipv4/netfilter.o net/ipv4/netfilter/built-in.a net/ipv4/tcp_cubic.o net/ipv4/tcp_bpf.o net/ipv4/udp_bpf.o net/ipv4/cipso_ipv4.o net/ipv4/netlat.o net/ipv4/xfrm4_policy.o net/ipv4/xfrm4_state.o net/ipv4/xfrm4_input.o net/ipv4/xfrm4_output.o net/ipv4/xfrm4_protocol.o net/ipv4/bpf_tcp_ca.o


clang -Wp,-MD,net/ipv6/.route.o.d  -nostdinc -isystem /usr/bin/../lib/clang/19/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Qunused-arguments -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Wno-format-security -std=gnu89 -Werror=unknown-warning-option -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m64 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mstack-alignment=8 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -Wno-sign-compare -fno-asynchronous-unwind-tables -mretpoline-external-thunk -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -Wframe-larger-than=2048 -fstack-protector-strong -Wno-format-invalid-specifier -Wno-gnu -Wno-tautological-compare -mno-global-merge -Wno-unused-but-set-variable -Wno-unused-const-variable -g -pg -mfentry -DCC_USING_NOP_MCOUNT -DCC_USING_FENTRY -fno-lto -flto=thin -fsplit-lto-unit -fvisibility=hidden -Wdeclaration-after-statement -Wvla -Wno-pointer-sign -Wno-array-bounds -fno-strict-overflow -fno-merge-all-constants -fno-stack-check -Wno-error=date-time -Werror=incompatible-pointer-types -fmacro-prefix-map=./= -Wno-initializer-overrides -Wno-format -Wno-sign-compare -Wno-format-zero-length -Wno-pointer-to-enum-cast -Wno-unaligned-access -Wno-cast-function-type-strict    -DKBUILD_BASENAME='"route"' -DKBUILD_MODNAME='"ipv6"' -D__KBUILD_MODNAME=kmod_ipv6 -c -o net/ipv6/route.o net/ipv6/route.c

rm -f net/ipv6/built-in.a; llvm-ar cDPrST net/ipv6/built-in.a net/ipv6/route.o 
# rm -f net/ipv6/built-in.a; llvm-ar cDPrST net/ipv6/built-in.a net/ipv6/af_inet6.o net/ipv6/anycast.o net/ipv6/ip6_output.o net/ipv6/ip6_input.o net/ipv6/addrconf.o net/ipv6/addrlabel.o net/ipv6/route.o net/ipv6/ip6_fib.o net/ipv6/ipv6_sockglue.o net/ipv6/ndisc.o net/ipv6/udp.o net/ipv6/udplite.o net/ipv6/raw.o net/ipv6/icmp.o net/ipv6/mcast.o net/ipv6/reassembly.o net/ipv6/tcp_ipv6.o net/ipv6/ping.o net/ipv6/exthdrs.o net/ipv6/datagram.o net/ipv6/ip6_flowlabel.o net/ipv6/inet6_connection_/sock.o net/ipv6/udp_offload.o net/ipv6/seg6.o net/ipv6/fib6_notifier.o net/ipv6/sysctl_net_ipv6.o net/ipv6/ip6mr.o net/ipv6/xfrm6_policy.o net/ipv6/xfrm6_state.o net/ipv6/xfrm6_input.o net/ipv6/xfrm6_output.o net/ipv6/xfrm6_protocol.o net/ipv6/netfilter.o net/ipv6/fib6_rules.o net/ipv6/proc.o net/ipv6/syncookies.o net/ipv6/calipso.o net/ipv6/netfilter/built-in.a net/ipv6/addrconf_core.o net/ipv6/exthdrs_core.o net/ipv6/ip6_checksum.o net/ipv6/ip6_icmp.o net/ipv6/output_core.o net/ipv6/protocol.o net/ipv6/ip6_offload.o net/ipv6/tcpv6_offload.o net/ipv6/exthdrs_offload.o net/ipv6/inet6_hashtables.o net/ipv6/mcast_snoop.o


rm -f net/built-in.a; llvm-ar cDPrST net/built-in.a net/ipv4/built-in.a net/ipv6/built-in.a 

ld.lld -m elf_x86_64 --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 -r -o vmlinux.o -T .tmp_initcalls.lds --whole-archive arch/x86/kernel/head_64.o arch/x86/kernel/head64.o arch/x86/kernel/ebda.o arch/x86/kernel/platform-quirks.o net/built-in.a --no-whole-archive --start-group --end-group

# tools/objtool/objtool orc generate --duplicate --mcount --vmlinux --no-fp --no-unreachable --retpoline --uaccess vmlinux.o

# make -f ./scripts/Makefile.modpost MODPOST_VMLINUX=1
# scripts/mod/modpost  -a -o vmlinux.symvers vmlinux.o
# llvm-objcopy -j .modinfo -O binary vmlinux.o modules.builtin.modinfo

ld.lld --unresolved-symbols=ignore-all -m elf_x86_64 -z max-page-size=0x200000 --thinlto-cache-dir=.thinlto-cache -mllvm -import-instr-limit=5 -z noexecstack --build-id -X -o .tmp_vmlinux.btf -T ./arch/x86/kernel/vmlinux.lds --whole-archive vmlinux.o --no-whole-archive

pahole -J --skip_encoding_btf_enum64 .tmp_vmlinux.btf

bpftool btf dump file .tmp_vmlinux.btf | grep \'bpf_prog\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'bpf_map\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'file\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'inode\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'task_struct\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'sock\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'sock_common\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'seq_file\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'sk_buff\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'fib6_info\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'request_sock\' | grep STRUCT
bpftool btf dump file .tmp_vmlinux.btf | grep \'inte_sock\' | grep STRUCT